# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@antfu/utils-0.7.7" = {
      name = "_at_antfu_slash_utils";
      packageName = "@antfu/utils";
      version = "0.7.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@antfu/utils/-/utils-0.7.7.tgz";
        sha512 = "gFPqTG7otEJ8uP6wrhDv6mqwGWYZKNvAcCq6u9hOj0c+IKCEsY4L1oC9trPq2SaWIzAfHvqfBDxF591JkMf+kg==";
      };
    };
    "@unocss/autocomplete-0.55.7" = {
      name = "_at_unocss_slash_autocomplete";
      packageName = "@unocss/autocomplete";
      version = "0.55.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/autocomplete/-/autocomplete-0.55.7.tgz";
        sha512 = "pUPDEviRogpFw3s+ai9oBzScznClMcamfUoGcjjBiYx5HKS0CrkxOb8oKbEG0hCXi72luJiRgXnBZPC6TCNSPw==";
      };
    };
    "@unocss/config-0.55.7" = {
      name = "_at_unocss_slash_config";
      packageName = "@unocss/config";
      version = "0.55.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/config/-/config-0.55.7.tgz";
        sha512 = "+X6rPScyFEWbkZyCyM+HfoJhJNN+CEl2n2izWkm0kuDj3w9fY9B3f/0dsk+jmx/gJEI5Y797q9zspNMNDib1AA==";
      };
    };
    "@unocss/core-0.55.7" = {
      name = "_at_unocss_slash_core";
      packageName = "@unocss/core";
      version = "0.55.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/core/-/core-0.55.7.tgz";
        sha512 = "c+bWe844Xjlwc1EPwHj0+n3LpntJG7ELPbEOOxNIG+CQdcEX0l1G0rkM8+nKstJ9WJmgpf1HdJQLVMF62HXvhw==";
      };
    };
    "@unocss/extractor-arbitrary-variants-0.55.7" = {
      name = "_at_unocss_slash_extractor-arbitrary-variants";
      packageName = "@unocss/extractor-arbitrary-variants";
      version = "0.55.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/extractor-arbitrary-variants/-/extractor-arbitrary-variants-0.55.7.tgz";
        sha512 = "imK2g/frlo5Ag0uVB+C/Psyo5+9AnqhoRAgYa6gyrQ/TJnrnwf+M3jFngU9evIMHw92vig1DGfPa2ZId901DwQ==";
      };
    };
    "@unocss/preset-mini-0.55.7" = {
      name = "_at_unocss_slash_preset-mini";
      packageName = "@unocss/preset-mini";
      version = "0.55.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/preset-mini/-/preset-mini-0.55.7.tgz";
        sha512 = "ZCskE2uprjGkpQezEPM6KPMf84rIZEUNc1p2DxWVHaFUPRV24/JSNsO4PsKrQgNIb2dLQxzPNlMzQJI7ssdBXQ==";
      };
    };
    "@unocss/preset-uno-0.55.7" = {
      name = "_at_unocss_slash_preset-uno";
      packageName = "@unocss/preset-uno";
      version = "0.55.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/preset-uno/-/preset-uno-0.55.7.tgz";
        sha512 = "z4pCxOv/OU1ARo++cvbijWNW2zy/EVTMqJXa+SEep9b99wFXPQE3gaPvLdURp/e5f1PoxVyPZ6JiBknbClSDuA==";
      };
    };
    "@unocss/preset-wind-0.55.7" = {
      name = "_at_unocss_slash_preset-wind";
      packageName = "@unocss/preset-wind";
      version = "0.55.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@unocss/preset-wind/-/preset-wind-0.55.7.tgz";
        sha512 = "vLi0mtYDnvx3uYtBR4fSCR52T59drTUp3XVAAqQTbhvRctnSWm65MWE4G+gqdt2qQ9fM4SVCsxLLaXuJkI2eqw==";
      };
    };
    "defu-6.1.4" = {
      name = "defu";
      packageName = "defu";
      version = "6.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/defu/-/defu-6.1.4.tgz";
        sha512 = "mEQCMmwJu317oSz8CwdIOdwf3xMif1ttiM8LTufzc3g6kR+9Pe236twL8j3IYT1F7GfRgGcW6MWxzZjLIkuHIg==";
      };
    };
    "fzf-0.5.2" = {
      name = "fzf";
      packageName = "fzf";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fzf/-/fzf-0.5.2.tgz";
        sha512 = "Tt4kuxLXFKHy8KT40zwsUPUkg1CrsgY25FxA2U/j/0WgEDCk3ddc/zLTCCcbSHX9FcKtLuVaDGtGE/STWC+j3Q==";
      };
    };
    "jiti-1.21.0" = {
      name = "jiti";
      packageName = "jiti";
      version = "1.21.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jiti/-/jiti-1.21.0.tgz";
        sha512 = "gFqAIbuKyyso/3G2qhiO2OM6shY6EPP/R0+mkDbyspxKazh8BXDC5FiFsUjlczgdNz/vfra0da2y+aHrusLG/Q==";
      };
    };
    "lru-cache-10.2.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "10.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-10.2.0.tgz";
        sha512 = "2bIM8x+VAf6JT4bKAljS1qUWgMsqZRPGJS6FSahIMPVvctcNhyVp7AJu7quxOW9jwkryBReKZY5tY5JYv2n/7Q==";
      };
    };
    "unconfig-0.3.13" = {
      name = "unconfig";
      packageName = "unconfig";
      version = "0.3.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/unconfig/-/unconfig-0.3.13.tgz";
        sha512 = "N9Ph5NC4+sqtcOjPfHrRcHekBCadCXWTBzp2VYYbySOHW0PfD9XLCeXshTXjkPYwLrBr9AtSeU0CZmkYECJhng==";
      };
    };
    "vscode-jsonrpc-6.0.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-6.0.0.tgz";
        sha512 = "wnJA4BnEjOSyFMvjZdpiOwhSq9uDoK8e/kpRJDTaMYzwlkrhG1fwDIZI94CLsLzlCK5cIbMMtFlJlfR57Lavmg==";
      };
    };
    "vscode-languageserver-7.0.0" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-7.0.0.tgz";
        sha512 = "60HTx5ID+fLRcgdHfmz0LDZAXYEV68fzwG0JWwEPBode9NuMYTIxuYXPg4ngO8i8+Ou0lM7y6GzaYWbiDL0drw==";
      };
    };
    "vscode-languageserver-protocol-3.16.0" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.16.0.tgz";
        sha512 = "sdeUoAawceQdgIfTI+sdcwkiK2KU+2cbEYA0agzM2uqaUy2UpnnGHtWTHVEtS0ES4zHU0eMFRGN+oQgDxlD66A==";
      };
    };
    "vscode-languageserver-textdocument-1.0.11" = {
      name = "vscode-languageserver-textdocument";
      packageName = "vscode-languageserver-textdocument";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-textdocument/-/vscode-languageserver-textdocument-1.0.11.tgz";
        sha512 = "X+8T3GoiwTVlJbicx/sIAF+yuJAqz8VvwJyoMVhwEMoEKE/fkDmrqUgDMyBECcM2A2frVZIUj5HI/ErRXCfOeA==";
      };
    };
    "vscode-languageserver-types-3.16.0" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.16.0.tgz";
        sha512 = "k8luDIWJWyenLc5ToFQQMaSrqCHiLwyKPHKPQZ5zz21vM+vIVUSvsRpcbiECH4WR88K2XZqc4ScRcZ7nk/jbeA==";
      };
    };
  };
in
{
  "unocss-language-server-git+https://git@github.com/rogersanctus/unocss-language-server#main" = nodeEnv.buildNodePackage {
    name = "unocss-language-server";
    packageName = "unocss-language-server";
    version = "0.0.10";
    src = fetchgit {
      url = "https://git@github.com/rogersanctus/unocss-language-server";
      rev = "7ebd11ffc752244cdbb90e6944dfee12a4f48ead";
      sha256 = "78976744fa1746cbd5bf881c1aff5fef841d0fb5d9d9882462c7f45c37437ac0";
    };
    dependencies = [
      sources."@antfu/utils-0.7.7"
      sources."@unocss/autocomplete-0.55.7"
      sources."@unocss/config-0.55.7"
      sources."@unocss/core-0.55.7"
      sources."@unocss/extractor-arbitrary-variants-0.55.7"
      sources."@unocss/preset-mini-0.55.7"
      sources."@unocss/preset-uno-0.55.7"
      sources."@unocss/preset-wind-0.55.7"
      sources."defu-6.1.4"
      sources."fzf-0.5.2"
      sources."jiti-1.21.0"
      sources."lru-cache-10.2.0"
      sources."unconfig-0.3.13"
      sources."vscode-jsonrpc-6.0.0"
      sources."vscode-languageserver-7.0.0"
      sources."vscode-languageserver-protocol-3.16.0"
      sources."vscode-languageserver-textdocument-1.0.11"
      sources."vscode-languageserver-types-3.16.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "unocss language server";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
