#!/bin/sh
(
    echo "<!-- File auto-generated by $0 -->"
    virsh -c qemu:///system dumpxml win11-base
) > win11.xml
(
    echo "<!-- File auto-generated by $0 -->"
    virsh -c qemu:///system dumpxml gaming
) > gaming.xml
# (
#     echo "<!-- File auto-generated by $0 -->"
#     virsh -c qemu:///system dumpxml production
# ) > production.xml
